const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const [root,output]=process.argv.slice(2); assert.equal(process.env.GCLOUD_PROJECT,'demo-inkr8-local');assert.equal(process.env.FIRESTORE_EMULATOR_HOST,'127.0.0.1:8080');
const adapter=require(path.join(root,'lib/firebase/admin.js'));adapter.FieldValue=require('firebase-admin/firestore').FieldValue;const db=adapter.db;
const rows=[];async function test(name,fn){try{await fn();rows.push({name,pass:true})}catch(e){rows.push({name,pass:false,error:e.message})}}
function value(x){if(x===null)return{nullValue:null};if(typeof x==='string')return{stringValue:x};if(typeof x==='boolean')return{booleanValue:x};if(typeof x==='number')return Number.isInteger(x)?{integerValue:String(x)}:{doubleValue:x};if(Array.isArray(x))return{arrayValue:{values:x.map(value)}};return{mapValue:{fields:fields(x)}}}function fields(o){return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,value(v)]))}
async function auth(){const r=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-key',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"returnSecureToken":true}'});assert.equal(r.status,200);return r.json()}
async function request(p,account,method='GET',data=null,mask=[]){let url='http://127.0.0.1:8080/v1/projects/demo-inkr8-local/databases/(default)/documents/'+p;if(mask.length)url+='?'+mask.map(k=>'updateMask.fieldPaths='+k).join('&');const r=await fetch(url,{method,headers:{'Content-Type':'application/json',...(account?{Authorization:'Bearer '+account.idToken}:{})},body:data?JSON.stringify({fields:fields(data)}):undefined});return r.status}
function initial(uid){return{id:uid,name:'',email:null,merit:1000,meritCap:50000,meritHold:0,rating:0,reputation:0,bestScore:0,submissionsCount:0,savedSubmissionsCount:0,profileImageURL:'',bannerImageURL:'',achievements:[],joinedDate:Date.now(),rankedWinStreak:0,rankedLossStreak:0,currentlyInRanked:false,rankedSessionStartedAt:null,tournamentsPlayed:0,tournamentsWon:0,totalMeritEarned:0,tipsReceived:0,isPhilosopher:false,philosopherSince:null,hasChosenUsername:false,recentScores:[],isPlaced:false,placementMatchesPlayed:0,totalPlacementScore:0,currentStreak:0,lastSubmissionDay:0,hasSeenPlacementReveal:false}}
function submission(uid,id){return{id,authorId:uid,content:'Local security acceptance text.',timestamp:Date.now(),wordCount:5,characterCount:31,wordsUsed:[],gamemodeName:'STANDARD',topicId:null,themeId:null,evaluation:null,status:'PENDING',playmode:'PRACTICE',isSaved:false,matchResult:null,matchStatus:'UNMATCHED'}}
(async()=>{
 const a=await auth(),b=await auth();await db.collection('users').doc(a.localId).set(initial(a.localId));await db.collection('users').doc(b.localId).set(initial(b.localId));const sid='fin-security-'+Date.now();await db.collection('submissions').doc(sid).set({...submission(a.localId,sid),playmode:'TOURNAMENT'});await db.collection('seasons').doc('1999-01').set({status:'CLOSED',pendingCount:0});
 await test('owner profile read',async()=>assert.equal(await request('users/'+a.localId,a),200));
 await test('anonymous denied private profile',async()=>assert.equal(await request('users/'+a.localId,null),403));
 await test('cross user profile read denied',async()=>assert.equal(await request('users/'+a.localId,b),403));
 await test('cross user profile write denied',async()=>assert.equal(await request('users/'+a.localId,b,'PATCH',{rating:999},['rating']),403));
 for(const k of ['rating','merit','meritCap','meritHold','isPlaced','reputation','isPhilosopher'])await test('owner cannot forge '+k,async()=>assert.equal(await request('users/'+a.localId,a,'PATCH',{[k]:k.startsWith('is')?true:99999},[k]),403));
 await test('owner email update preserved',async()=>assert.equal(await request('users/'+a.localId,a,'PATCH',{email:null},['email']),200));
 await test('owner failure cleanup preserves session release',async()=>assert.equal(await request('users/'+a.localId,a,'PATCH',{currentlyInRanked:false,rankedSessionStartedAt:null},['currentlyInRanked','rankedSessionStartedAt']),200));
 await test('cannot enter Ranked without economic callable',async()=>assert.equal(await request('users/'+a.localId,a,'PATCH',{currentlyInRanked:true,rankedSessionStartedAt:Date.now()},['currentlyInRanked','rankedSessionStartedAt']),403));
 await test('owner submission read',async()=>assert.equal(await request('submissions/'+sid,a),200));
 await test('other user submission read denied',async()=>assert.equal(await request('submissions/'+sid,b),403));
 await test('other user submission write denied',async()=>assert.equal(await request('submissions/'+sid,b,'PATCH',{content:'forged'},['content']),403));
 await test('owner cannot forge evaluation',async()=>assert.equal(await request('submissions/'+sid,a,'PATCH',{status:'EVALUATED'},['status']),403));
 await test('owner cannot rewrite confirmed submission',async()=>assert.equal(await request('submissions/'+sid,a,'PATCH',{content:'rewrite'},['content']),403));
 await test('owner cannot erase pending submission',async()=>assert.equal(await request('submissions/'+sid,a,'DELETE'),403));
 for(const collection of ['seasons','seasons/1999-01/members','seasonAssignments','users/'+a.localId+'/meritTransactions','tournaments','leagues'])await test('client cannot write admin '+collection,async()=>assert.equal(await request(collection+'/forged',a,'PATCH',{rating:999999}),403));
 await test('seasons accessed through callable, not private client documents',async()=>assert.equal(await request('seasons/1999-01',a),403));
 await test('new genuine Users defaults accepted',async()=>{const c=await auth();assert.equal(await request('users/'+c.localId,c,'PATCH',initial(c.localId)),200)});
 await test('new forged grant rejected',async()=>{const c=await auth();assert.equal(await request('users/'+c.localId,c,'PATCH',{...initial(c.localId),merit:99999}),403)});
 await test('new genuine Practice payload accepted',async()=>{const id=sid+'-practice';assert.equal(await request('submissions/'+id,a,'PATCH',submission(a.localId,id)),200)});
 await test('new foreign author rejected',async()=>{const id=sid+'-foreign';assert.equal(await request('submissions/'+id,b,'PATCH',submission(a.localId,id)),403)});
 await test('Ranked without paid session rejected',async()=>{const id=sid+'-ranked';assert.equal(await request('submissions/'+id,b,'PATCH',{...submission(b.localId,id),playmode:'RANKED'}),403)});
 for(const c of ['words','themes','topics']){await db.collection(c).doc('fin-catalog').set({name:'Local catalog',randomIndex:.5});await test('authenticated '+c+' catalog read',async()=>assert.equal(await request(c+'/fin-catalog',a),200));await test('catalog '+c+' write forbidden',async()=>assert.equal(await request(c+'/fin-catalog',a,'PATCH',{name:'forged'},['name']),403));}
 await test('initializer repetition preserves progress',async()=>{const uid='fin-initializer-'+Date.now(),ref=db.collection('users').doc(uid);await ref.set({...initial(uid),rating:555,merit:3456,isPlaced:true,name:'Existing'});const before=(await ref.get()).data();await require(process.argv[4] || path.join(root,'lib/users/userInitializer.js')).createUserProfile.run({uid});assert.deepEqual((await ref.get()).data(),before)});
 fs.writeFileSync(output,JSON.stringify({passed:rows.filter(r=>r.pass).length,failed:rows.filter(r=>!r.pass).length,rows,transport:'Real emulator REST with anonymous Auth ID tokens; Admin SDK fixtures. No tokens recorded.',project:'demo-inkr8-local'},null,2)+'\n');console.log(JSON.stringify({passed:rows.filter(r=>r.pass).length,failed:rows.filter(r=>!r.pass).length}));await db.terminate();if(rows.some(r=>!r.pass))process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exitCode=1});
